dist: trusty
sudo: false

language: go

go:
  - 1.x

branches:
  only:
    - master

env:
  - CONSUL_VERSION=1.2.2

before_install:
  - curl -sLo consul.zip https://releases.hashicorp.com/consul/${CONSUL_VERSION}/consul_${CONSUL_VERSION}_linux_amd64.zip
  - unzip consul.zip
  - mkdir -p ~/bin
  - mv consul ~/bin
  - export PATH="~/bin:$PATH"

script: make test